/-
Copyright (c) 2026 QuAIR.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: QuAIR Team, Chengkai Zhu
-/

module

public import QIT.Coding.Private.ExplicitChannel

/-!
# Exact radical forms for the finite simulator certificate

These sparse tables use the field generated by √2, √3, √5 and √7.
`ks_eq`, `as_eq` and `bs_eq` prove their equality to the manuscript's
binomial formulas by exact arithmetic and nonnegative square roots.
The tables are proof aids, not assumed certificate inputs.
-/

@[expose] public section
namespace QIT
open Channel
noncomputable section

namespace SimulatorCanonical
def r2 : ℂ := ↑(Real.sqrt 2)
@[simp] lemma r2_star : star r2 = r2 := by
  simp only [r2, Complex.star_def, Complex.conj_ofReal]
@[simp] lemma r2_conj : (starRingEnd ℂ) r2 = r2 := r2_star
@[simp] lemma r2_sq : r2^2 = 2 := by
  norm_num [r2, ← Complex.ofReal_pow, Real.sq_sqrt]
def r3 : ℂ := ↑(Real.sqrt 3)
@[simp] lemma r3_star : star r3 = r3 := by
  simp only [r3, Complex.star_def, Complex.conj_ofReal]
@[simp] lemma r3_conj : (starRingEnd ℂ) r3 = r3 := r3_star
@[simp] lemma r3_sq : r3^2 = 3 := by
  norm_num [r3, ← Complex.ofReal_pow, Real.sq_sqrt]
def r5 : ℂ := ↑(Real.sqrt 5)
@[simp] lemma r5_star : star r5 = r5 := by
  simp only [r5, Complex.star_def, Complex.conj_ofReal]
@[simp] lemma r5_conj : (starRingEnd ℂ) r5 = r5 := r5_star
@[simp] lemma r5_sq : r5^2 = 5 := by
  norm_num [r5, ← Complex.ofReal_pow, Real.sq_sqrt]
def r7 : ℂ := ↑(Real.sqrt 7)
@[simp] lemma r7_star : star r7 = r7 := by
  simp only [r7, Complex.star_def, Complex.conj_ofReal]
@[simp] lemma r7_conj : (starRingEnd ℂ) r7 = r7 := r7_star
@[simp] lemma r7_sq : r7^2 = 7 := by
  norm_num [r7, ← Complex.ofReal_pow, Real.sq_sqrt]
def ks : Fin 8 → CMatrix (Fin 4) :=
  ![![![(1 / 6) * r2 * r3, 0, 0, 0], ![0, (1 / 6) * r2 * r3, 0, 0], ![0, 0, (1 / 6) * r2 * r3, 0],
    ![0, 0, 0, (1 / 6) * r2 * r3]],
    ![![0, 0, 0, (1 / 21) * r2 * r3 * r5 * r7], ![0, 0, 0, 0], ![0, 0, 0, 0], ![0, 0, 0, 0]],
    ![![0, 0, -((1 / 21) * r3 * r5 * r7), 0], ![0, 0, 0, (1 / 21) * r3 * r5 * r7], ![0, 0, 0, 0],
      ![0, 0, 0, 0]],
    ![![0, (1 / 21) * r2 * r3 * r7, 0, 0], ![0, 0, -((1 / 7) * r2 * r7), 0], ![0, 0, 0, (1 / 21) *
      r2 * r3 * r7], ![0, 0, 0, 0]],
    ![![-((1 / 42) * r2 * r3 * r7), 0, 0, 0], ![0, (1 / 14) * r2 * r3 * r7, 0, 0], ![0, 0, -((1 /
      14) * r2 * r3 * r7), 0], ![0, 0, 0, (1 / 42) * r2 * r3 * r7]],
    ![![0, 0, 0, 0], ![-((1 / 21) * r2 * r3 * r7), 0, 0, 0], ![0, (1 / 7) * r2 * r7, 0, 0], ![0, 0,
      -((1 / 21) * r2 * r3 * r7), 0]],
    ![![0, 0, 0, 0], ![0, 0, 0, 0], ![-((1 / 21) * r3 * r5 * r7), 0, 0, 0], ![0, (1 / 21) * r3 * r5
      * r7, 0, 0]],
    ![![0, 0, 0, 0], ![0, 0, 0, 0], ![0, 0, 0, 0], ![-((1 / 21) * r2 * r3 * r5 * r7), 0, 0, 0]]]

def as : Fin 4 → Matrix (Fin 4) (Fin 8) ℂ :=
  ![![![0, (1 / 7) * r5 * r7, 0, 0, 0, 0, 0, 0], ![0, 0, (1 / 14) * r2 * r5 * r7, 0, 0, 0, 0, 0],
    ![0, 0, 0, (1 / 7) * r7, 0, 0, 0, 0], ![(1 / 2), 0, 0, 0, (1 / 14) * r7, 0, 0, 0]],
    ![![0, 0, (1 / 14) * r2 * r5 * r7, 0, 0, 0, 0, 0], ![0, 0, 0, (1 / 7) * r3 * r7, 0, 0, 0, 0],
      ![-((1 / 2)), 0, 0, 0, (3 / 14) * r7, 0, 0, 0], ![0, 0, 0, 0, 0, (1 / 7) * r7, 0, 0]],
    ![![0, 0, 0, (1 / 7) * r7, 0, 0, 0, 0], ![(1 / 2), 0, 0, 0, (3 / 14) * r7, 0, 0, 0], ![0, 0, 0,
      0, 0, (1 / 7) * r3 * r7, 0, 0], ![0, 0, 0, 0, 0, 0, (1 / 14) * r2 * r5 * r7, 0]],
    ![![-((1 / 2)), 0, 0, 0, (1 / 14) * r7, 0, 0, 0], ![0, 0, 0, 0, 0, (1 / 7) * r7, 0, 0], ![0, 0,
      0, 0, 0, 0, (1 / 14) * r2 * r5 * r7, 0], ![0, 0, 0, 0, 0, 0, 0, (1 / 7) * r5 * r7]]]

def bs : Fin 10 → Matrix (Fin 4) (Fin 8) ℂ :=
  ![![![0, 0, 0, 0, 0, 0, 0, 0], ![0, 0, 0, 0, 0, 0, 0, 0], ![0, 0, 0, 0, 0, 0, 0, 0], ![0, (1 / 5)
    * r5, 0, 0, 0, 0, 0, 0]],
    ![![0, 0, 0, 0, 0, 0, 0, 0], ![0, 0, 0, 0, 0, 0, 0, 0], ![0, -((1 / 15) * r3 * r5), 0, 0, 0, 0,
      0, 0], ![0, 0, (1 / 15) * r2 * r3 * r5, 0, 0, 0, 0, 0]],
    ![![0, 0, 0, 0, 0, 0, 0, 0], ![0, (1 / 30) * r3 * r5, 0, 0, 0, 0, 0, 0], ![0, 0, -((1 / 10) * r2
      * r5), 0, 0, 0, 0, 0], ![0, 0, 0, (1 / 6) * r3, 0, 0, 0, 0]],
    ![![0, -((1 / 210) * r3 * r5 * r7), 0, 0, 0, 0, 0, 0], ![0, 0, (1 / 70) * r2 * r3 * r5 * r7, 0,
      0, 0, 0, 0], ![0, 0, 0, -((1 / 14) * r3 * r7), 0, 0, 0, 0], ![0, 0, 0, 0, (1 / 21) * r3 * r7,
      0, 0, 0]],
    ![![0, 0, -((1 / 105) * r3 * r5 * r7), 0, 0, 0, 0, 0], ![0, 0, 0, (1 / 14) * r2 * r7, 0, 0, 0,
      0], ![0, 0, 0, 0, -((1 / 21) * r2 * r3 * r7), 0, 0, 0], ![0, 0, 0, 0, 0, (1 / 42) * r2 * r3 *
      r7, 0, 0]],
    ![![0, 0, 0, -((1 / 42) * r2 * r3 * r7), 0, 0, 0, 0], ![0, 0, 0, 0, (1 / 21) * r2 * r3 * r7, 0,
      0, 0], ![0, 0, 0, 0, 0, -((1 / 14) * r2 * r7), 0, 0], ![0, 0, 0, 0, 0, 0, (1 / 105) * r3 * r5
      * r7, 0]],
    ![![0, 0, 0, 0, -((1 / 21) * r3 * r7), 0, 0, 0], ![0, 0, 0, 0, 0, (1 / 14) * r3 * r7, 0, 0],
      ![0, 0, 0, 0, 0, 0, -((1 / 70) * r2 * r3 * r5 * r7), 0], ![0, 0, 0, 0, 0, 0, 0, (1 / 210) * r3
      * r5 * r7]],
    ![![0, 0, 0, 0, 0, -((1 / 6) * r3), 0, 0], ![0, 0, 0, 0, 0, 0, (1 / 10) * r2 * r5, 0], ![0, 0,
      0, 0, 0, 0, 0, -((1 / 30) * r3 * r5)], ![0, 0, 0, 0, 0, 0, 0, 0]],
    ![![0, 0, 0, 0, 0, 0, -((1 / 15) * r2 * r3 * r5), 0], ![0, 0, 0, 0, 0, 0, 0, (1 / 15) * r3 *
      r5], ![0, 0, 0, 0, 0, 0, 0, 0], ![0, 0, 0, 0, 0, 0, 0, 0]],
    ![![0, 0, 0, 0, 0, 0, 0, -((1 / 5) * r5)], ![0, 0, 0, 0, 0, 0, 0, 0], ![0, 0, 0, 0, 0, 0, 0, 0],
      ![0, 0, 0, 0, 0, 0, 0, 0]]]

set_option maxHeartbeats 6000000 in
lemma ks_eq : ks = krausN := by
  funext k i j
  fin_cases k <;> fin_cases i <;> fin_cases j <;>
    norm_num [ks, r2, r3, r5, r7, krausN, tM, yM, Matrix.mul_apply,
      Matrix.smul_apply, Fin.sum_univ_succ, Nat.choose]
  all_goals simp only [← Complex.ofReal_mul, ← Complex.ofReal_div,
    ← Complex.ofReal_inv, ← Complex.ofReal_ofNat, ← Complex.ofReal_one, Complex.ofReal_inj]
  all_goals apply (sq_eq_sq₀ (by positivity) (by positivity)).mp
  all_goals norm_num [mul_pow, div_pow, inv_pow, Real.sq_sqrt]


set_option maxHeartbeats 6000000 in
lemma as_eq : as = simulatorKrausA := by
  funext j c ℓ
  fin_cases j <;> fin_cases c <;> fin_cases ℓ <;>
    norm_num [as, r2, r3, r5, r7, simulatorKrausA, Nat.choose]
  all_goals simp only [← Complex.ofReal_mul, ← Complex.ofReal_div,
    ← Complex.ofReal_ofNat, ← Complex.ofReal_one, Complex.ofReal_inj]
  all_goals apply (sq_eq_sq₀ (by positivity) (by positivity)).mp
  all_goals norm_num [mul_pow, div_pow, inv_pow, Real.sq_sqrt]

set_option maxHeartbeats 6000000 in
lemma bs_eq : bs = simulatorKrausB := by
  funext t c ℓ
  fin_cases t <;> fin_cases c <;> fin_cases ℓ <;>
    norm_num [bs, r2, r3, r5, r7, simulatorKrausB, Nat.choose]
  all_goals simp only [← Complex.ofReal_mul, ← Complex.ofReal_div,
    ← Complex.ofReal_inv, ← Complex.ofReal_ofNat, ← Complex.ofReal_one, Complex.ofReal_inj]
  all_goals apply (sq_eq_sq₀ (by positivity) (by positivity)).mp
  all_goals norm_num [mul_pow, div_pow, inv_pow, Real.sq_sqrt]

@[simp] lemma r2_cube : r2^3 = 2 * r2 := by
  rw [pow_succ, r2_sq]
@[simp] lemma r2_four : r2^4 = 4 := by
  rw [show 4 = 2*2 by decide, pow_mul, r2_sq]
  norm_num

@[simp] lemma r3_cube : r3^3 = 3 * r3 := by
  rw [pow_succ, r3_sq]
@[simp] lemma r3_four : r3^4 = 9 := by
  rw [show 4 = 2*2 by decide, pow_mul, r3_sq]
  norm_num

@[simp] lemma r5_cube : r5^3 = 5 * r5 := by
  rw [pow_succ, r5_sq]
@[simp] lemma r5_four : r5^4 = 25 := by
  rw [show 4 = 2*2 by decide, pow_mul, r5_sq]
  norm_num

@[simp] lemma r7_cube : r7^3 = 7 * r7 := by
  rw [pow_succ, r7_sq]
@[simp] lemma r7_four : r7^4 = 49 := by
  rw [show 4 = 2*2 by decide, pow_mul, r7_sq]
  norm_num

def ds : Sum (Fin 4) (Fin 10) → Matrix (Fin 4) (Fin 8) ℂ := Sum.elim as bs
lemma ds_eq : ds = simulatorKraus := by
  funext s
  cases s <;> simp [ds, simulatorKraus, as_eq, bs_eq]

lemma ofKraus_single_apply {a b κ : Type*} [Fintype a] [DecidableEq a]
    [Fintype b] [DecidableEq b] [Fintype κ] (K : κ → Matrix b a ℂ) (i j : a) (r s : b) :
    MatrixMap.ofKraus K (Matrix.single i j 1) r s =
      ∑ k, K k r i * star (K k s j) := by
  simp [MatrixMap.ofKraus, Matrix.sum_apply, Matrix.mul_apply, Matrix.conjTranspose_apply,
    Matrix.single_apply, ite_and]

lemma complement_single_apply {a b κ : Type*} [Fintype a] [DecidableEq a]
    [Fintype b] [DecidableEq b] [Fintype κ] [DecidableEq κ]
    (K : κ → Matrix b a ℂ) (i j : a) (r s : κ) :
    MatrixMap.complementOfKraus K (Matrix.single i j 1) r s =
      ∑ k, K r k i * star (K s k j) := by
  rw [MatrixMap.complementOfKraus_eq_ofKraus]
  exact ofKraus_single_apply _ _ _ _ _

end SimulatorCanonical
end
end QIT
